on: push
name: Lints and tests
jobs:
  lints-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build -j
      - run: make fmt-check
      - run: make lint -j
      - run: make test
      - name: Example in readme corresponds to example
        run: '[[ "$(cat README.md)" = *"$(cat bin/readme-example.c)"* ]]'
